n = 4
t = 1
t_reconstruction = 2
start_time = "2025-09-02T11:36:30Z"

[[nodes]]
id = 1
start_time = "2025-07-24T16:25:30Z"
multiaddr = "/ip4/127.0.0.1/tcp/9991"
adkg_pk = "wh56dvt1W5Y2EL/LGEZ1nuDBJuxxuK1fAdsqLWl95nY="
peer_id = "12D3KooWM3qqCBqhVmGvSCTPPiLeUgNUF8iryU1TVDtgcsYmbVYe"

[[nodes]]
id = 2
multiaddr = "/ip4/127.0.0.1/tcp/9992"
adkg_pk = "2iXd3IJReepD6qsRoYocSaAJCKbsJlCvPNGzDHd9ewg="
peer_id = "12D3KooWJoqoQhzfYjgGNoKweAQweFe82VJ8kHHrtFcXKc86bPu5"

[[nodes]]
id = 3
adkg_pk = "0PDy8jXgWNMV08W+7wEKlT98wWR2BDTCq9rbaAdgOqs="
multiaddr = "/ip4/127.0.0.1/tcp/9993"
peer_id = "12D3KooWSGC5zAQtBjjtgUYWNGrQUwfxA9eEJ1NqAnSJVXaRbr5c"

[[nodes]]
id = 4
multiaddr = "/ip4/127.0.0.1/tcp/9994"
adkg_pk = "hEbngMlOF+HlyvFOrbeTWzufVPd3gyqcpuoTwAV4fZc="
peer_id = "12D3KooWKB1ze4BrNc888Ub9ydjt9HFBUV9sgmmEFVtCqWET4S4B"
