app_name = "lol"
curve_id = "Bn254G1"
hash_id = "Keccak256"
adkg_version = "v0.1"
generator_g = "wkZgBS9UCjTEJ5TZL7xxTx134zzKjzfGR6XRYHm5jXs="
generator_h = "lKeVzVvFvciHswz8u42NYDtxcEpFTsWM5fmJ+SGnaLo="
adkg_scheme_name = "DXKR23-Bn254G1-Keccak256"
output_generator = "mY6Tk5INSDpyYL+3MftdJfGqSTM1qecSl+SFt67zEsIYAN7vEh8edkJqAGZeXER5Z0Mi1Pde2t1G3r1c2ZL27Q=="


