name: Rust CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust 🔧
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Cargo registry 🔧
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo index 🔧
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Cache Cargo build 🔧
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Install dependencies 🔧
        run: cargo fetch

      - name: Run cargo fmt (lint) 🔧
        run: cargo fmt --check

      - name: Run Clippy (lint) 🔧
        run: cargo clippy --all-targets --all-features

      - name: Run tests 🧪
        run: cargo test --all-features --lib --bins --tests # omit bench target

      - name: Build project 👷
        run: cargo build --release
