name: 'Rust Test Action'
description: 'Runs format check, clippy, and tests for a Rust crate'
inputs:
  working-directory:
    required: true
    description: 'Directory containing the Rust crate'
  additional-flags:
    required: false
    default: ''
    description: 'Additional flags for cargo commands'

runs:
  using: "composite"
  steps:
    # Pull cargo nextest binaries
    - uses: taiki-e/install-action@v2
      with:
        tool: nextest

    - name: Check formatting
      working-directory: ${{ inputs.working-directory }}
      run: cargo fmt --check ${{ inputs.additional-flags }}
      shell: bash

    - name: Check clippy
      working-directory: ${{ inputs.working-directory }}
      run: cargo clippy --all-features --all-targets -- -Dwarnings ${{ inputs.additional-flags }}
      shell: bash

    - name: Run all tests
      working-directory: ${{ inputs.working-directory }}
      run: cargo nextest run
      shell: bash
