[package]
name = "gen-keys"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true

# crypto
ark-poly.workspace = true
ark-std.workspace = true
ark-bn254.workspace = true
ark-bls12-381.workspace = true
ark-ec.workspace = true
ark-ff.workspace = true
utils.workspace = true

# network
libp2p = { workspace = true, features = ["serde"] }

# misc
clap = { workspace = true }
base64 = { workspace = true }
hex.workspace = true
rand.workspace = true
strum.workspace = true
