[package]
name = "silent-threshold-encryption"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { version = "0.5.0", features = [ "html_reports" ] }
ark-std = { version = "0.4.0" }
ark-ec = { version = "0.4.0" }
ark-ff = { version = "0.4.0" }
ark-poly = { version = "0.4.0" }
ark-bls12-381 = { version = "0.4.0" }
ark-serialize = { version = "0.4.0" }
sha3 = "0.10"
rand = "0.8.5"
thiserror = "1.0.61"
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
base64 = { version = "0.22", optional = true}

[dev-dependencies]
anyhow = "1.0"
ark-bn254 = "0.4.0"
num-bigint = "0.4.6"
chacha20poly1305 = "0.10"

[features]
asm = [ "ark-ff/asm" ]
serde = ["dep:serde", "dep:serde_json", "dep:base64"]

[profile.dev]
opt-level = 3

[[bench]]
name = "encryption"
harness = false

[[bench]]
name = "decryption"
harness = false

[[bench]]
name = "interpolation"
harness = false

[[bench]]
name = "setup"
harness = false
