name: Build Docker Image

on:
  workflow_call:
    inputs:
      binary_name:
        required: true
        type: string
      binary_path:
        required: true
        type: string
      image_name:
        required: true
        type: string
      description:
        required: true
        type: string
      docker_registry:
        required: true
        type: string
      test_mode:
        required: false
        type: string
        default: 'false'
    secrets:
      GCP_SERVICE_ACCOUNT_TOKEN:
        required: true

env:
  IMAGE_MAINTAINER: "Randamu"
  IMAGE_VENDOR: "Randamu"

jobs:
  build:
    name: ${{ inputs.image_name }}
    runs-on: ["randamu-self-hosted-default"]
    steps:
      - name: Download Docker build context
        uses: actions/download-artifact@v4
        with:
          name: docker-context-${{ github.sha }}
          path: .

      - name: Download pre-built binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries-${{ github.sha }}
          path: target/release

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.docker_registry }}/${{ inputs.image_name }}
          labels: |
            maintainer=${{ env.IMAGE_MAINTAINER }}
            org.opencontainers.image.vendor=${{ env.IMAGE_VENDOR }}
            org.opencontainers.image.title=${{ inputs.image_name }}
            org.opencontainers.image.description=${{ inputs.description }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=main-latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"]
          driver-opts: |
            image=mirror.gcr.io/moby/buildkit:buildx-stable-1
            network=host

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') || inputs.test_mode == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BINARY_PATH=${{ inputs.binary_path }}
            BINARY_NAME=${{ inputs.binary_name }}
          cache-from: |
            type=registry,ref=${{ inputs.docker_registry }}/${{ inputs.image_name }}-cache:${{ steps.meta.outputs.version }}
            type=registry,ref=${{ inputs.docker_registry }}/${{ inputs.image_name }}-cache:main
          cache-to: type=registry,ref=${{ inputs.docker_registry }}/${{ inputs.image_name }}-cache:${{ steps.meta.outputs.version }},mode=max
