name: Go
on:
  push:
    paths:
      - '**.go'
      - '**.proto'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache-dependency-path: onlyswaps-verifier/go.sum

      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "latest"

      - name: Install protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: Install protoc-gen-go-grpc
        run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Generate proto files
        run: go generate -C ./onlyswaps-verifier ./...

      - name: Build
        run: go build -C ./onlyswaps-verifier -v ./...
      
      - name: Test with the Go CLI
        run: go test -C ./onlyswaps-verifier -v ./...
