name: Go
on:
  push:
    paths:
      - '**.go'
      - '**.proto'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache-dependency-path: onlyswaps-verifier/go.sum

      - name: Generate proto files
        run: go generate -C ./onlyswaps-verifier ./...

      - name: Build
        run: go build -C ./onlyswaps-verifier -v ./...
      
      - name: Test with the Go CLI
        run: go test -C ./onlyswaps-verifier -v ./...
